version: '3.9'

services:
  flask_app:
    container_name: flask_app
    image: vedeshp/flask-crud-learning:1.0.0
    build: .
    ports:
      - "4002:4002"
    environment:
      - DB_URL=postgresql://postgres@flask_db:5432/postgres
    depends_on:
      - flask_db
    
  flask_db:
    container_name: flask_db
    image: caiorss/postgres-docker-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/posgresql/data

volumes:
  pgdata: {}